DROP SCHEMA IF EXISTS STUDENT_INFO;
SET NAMES utf8;
CREATE SCHEMA STUDENT_INFO;
USE STUDENT_INFO;

CREATE TABLE TEACHER  (TeacherId INTEGER PRIMARY KEY,  TeacherName VARCHAR(255) NOT NULL, Position VARCHAR(255) NOT NULL);

CREATE TABLE COURSE (CourseId INTEGER PRIMARY KEY, CourseTitle VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE ST_GROUP (GroupNumber INTEGER PRIMARY KEY, Specialization VARCHAR(255) NOT NULL);

CREATE TABLE STUDENT
  (StudentId INTEGER AUTO_INCREMENT PRIMARY KEY, 
   StudentName VARCHAR(255) NOT NULL, 
   GroupNumber INTEGER, 
   BirthDate DATE, 
   Address VARCHAR(255));
   
ALTER TABLE STUDENT ADD CONSTRAINT GROUP_ST_FK FOREIGN KEY(GroupNumber) REFERENCES ST_GROUP(GroupNumber);

CREATE TABLE PHONE_LIST
			(StudentId INTEGER NOT NULL, PhoneType CHAR(12),  Phone CHAR(11) NOT NULL);

ALTER TABLE PHONE_LIST ADD CONSTRAINT ST_PH_FK FOREIGN KEY(StudentId) REFERENCES STUDENT(StudentId); 

CREATE TABLE EXAM_SHEET (ExamSheetId INTEGER PRIMARY KEY, GroupNumber INTEGER NOT NULL, CourseId INTEGER NOT NULL, TeacherId INTEGER, ClassRoom INTEGER, ExamDate DATE);
ALTER TABLE EXAM_SHEET ADD CONSTRAINT COURSE_EX_SHEET_FK FOREIGN KEY(CourseId) REFERENCES COURSE(CourseId);
ALTER TABLE EXAM_SHEET ADD CONSTRAINT TEACHER_EX_SHEET_FK FOREIGN KEY(TeacherId) REFERENCES TEACHER(TeacherId);
ALTER TABLE EXAM_SHEET ADD CONSTRAINT GROUP_EX_SHEET_FK FOREIGN KEY(GroupNumber) REFERENCES  ST_GROUP(GroupNumber);

CREATE TABLE EXAM_RESULT (StudentId INTEGER NOT NULL, ExamSheetId INTEGER NOT NULL, Mark SMALLINT CHECK (MARK > 0 AND MARK <= 5));
ALTER TABLE EXAM_RESULT ADD CONSTRAINT ST_EX_FK FOREIGN KEY(StudentId) REFERENCES STUDENT(StudentId);
ALTER TABLE EXAM_RESULT ADD CONSTRAINT EXR_EXT_FK FOREIGN KEY(ExamSheetId)REFERENCES EXAM_SHEET(ExamSheetId);
ALTER TABLE EXAM_RESULT ADD CONSTRAINT PK_EXAM_RESULT PRIMARY KEY(StudentId, ExamSheetId);